services:
  - type: worker
    name: safep2p-bot
    runtime: node
    rootDir: bot
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
